[package]
name = "surrealist"
version = "0.0.0"
description = "Powerful graphical SurrealDB query playground and database explorer for Browser and Desktop"
authors = ["SurrealDB"]
license = "MIT"
repository = "https://github.com/surrealdb/surrealist"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
tauri = { version = "1.6.1", features = [ "updater", "window-maximize", "window-unmaximize", "os-all", "window-start-dragging", "path-all", "dialog-open", "fs-read-file", "devtools", "dialog-save", "fs-write-file", "shell-open", "window-set-always-on-top", "window-set-title", "window-show"] }
# tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
portpicker = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "0.18.2" # if tauri build fails, make sure to match this version to what we have in tauri
openssl = { version = "0.10.64", features = ["vendored"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.25.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
