name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      # This step is required to run following steps, as they require the `dist` directory
      - name: Build frontend
        run: pnpm install --no-frozen-lockfile && pnpm build

      - name: Check formatting
        run: |
          cd src-tauri
          cargo fmt --all -- --check
          cd ..

      - name: Test Tauri
        run: |
          cd src-tauri
          cargo test --all-features
          cd ..

      - name: Clippy
        run: |
          cd src-tauri
          cargo clippy -- -D warnings
          cd ..
